language: java
jdk:
- openjdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: bFQ5xxla3p0Y6ry3EWZZonNPWiAAuCekCvErg5FWIq4C6G5VOyl8oYW8T2aRYjeWPZmHzdjme1eptZvwlLpRdekjnRhGRoJhDyam9mtMbAa6H4cqGiJAFXG1RaJeOy2199h2a4mf2Ldy4lxGFrA8tfuLqsXogPnZS5snuOQw9sY=
  file: build/libs/rundeck-ec2-nodes-plugin-*.jar
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: rundeck-plugins/rundeck-ec2-nodes-plugin
notifications:
  email: false
  slack:
    secure: bNG71NV9O9NIoVzWS2LenTc8Nq5uqIjJ7h6UOW8eMMLi65nCEubhMW+ideRuX8BRjXjhemvfdu0euuHHL2rHlQQ+tyMsdg0svy5VtpQcCc8l0KxptNgh9q+2Cw8znSzy1egbAWBd+uud+WZ4gydRt8medrv+ed5fPfUQcwCY9R4=
